apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: Never

  nodeSelector:
    nvidia.com/gpu.present: "true"

  tolerations:
  - key: "gpu-only"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

  containers:
  - name: cuda
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["bash", "-c"]
    args:
      - nvidia-smi && sleep 3600
    resources:
      limits:
        nvidia.com/gpu: 1